# Generated by Django 3.1.2 on 2020-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201026_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавить фото', upload_to='main/static/avatar/%Y/%m/%d'),
        ),
    ]
