# Generated by Django 3.1.2 on 2020-11-05 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201026_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=600, verbose_name='Название парикмахерской')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, unique=True)),
                ('address', models.CharField(max_length=600, verbose_name='Адресс')),
                ('tel', models.CharField(blank=True, max_length=17, null=True, verbose_name='Номер телефона')),
                ('social', models.CharField(max_length=600, verbose_name='Адресс')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.TextField(max_length=1500, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Контакты',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
