# Generated by Django 3.1.2 on 2020-11-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('name',), 'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Описание'),
        ),
    ]
