# Generated by Django 3.1.2 on 2020-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201105_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='social',
            field=models.CharField(max_length=600, verbose_name='социальные сети'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
