# Generated by Django 3.1.2 on 2020-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201105_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавить фото', upload_to='main/static/contacts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.TextField(blank=True, max_length=1500, verbose_name='О Нас'),
        ),
    ]
