# Generated by Django 3.1.2 on 2020-11-05 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201105_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=600, verbose_name='Название парикмахерской')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('theme', models.CharField(max_length=600, verbose_name='Адресс')),
                ('contact', models.TextField(blank=True, max_length=1500, verbose_name='О Нас')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
