# Generated by Django 3.1.2 on 2020-11-13 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201113_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название скидки')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, unique=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='% скидки')),
                ('word', models.CharField(blank=True, max_length=254, null=True, verbose_name='кодовое слово')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
                ('image', models.ImageField(blank=True, help_text='Добавить фото', upload_to='main/static/contacts/%Y/%m/%d')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
