# Generated by Django 3.1.2 on 2020-11-13 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя мастера')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, unique=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='word',
            field=models.CharField(max_length=254, verbose_name='Условие акции'),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Добавить фото', upload_to='main/static/contacts/%Y/%m/%d')),
                ('master_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='main.masters')),
            ],
        ),
    ]
