# Generated by Django 3.1.2 on 2020-11-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='master_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.masters'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, help_text='Добавить фото', upload_to='main/static/masters/%Y/%m/%d'),
        ),
    ]
