# Generated by Django 3.1.2 on 2020-11-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201114_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='example1',
            field=models.ImageField(blank=True, help_text='Примеры работ', upload_to='main/static/masters/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='masters',
            name='example2',
            field=models.ImageField(blank=True, help_text='Примеры работ', upload_to='main/static/masters/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='masters',
            name='example3',
            field=models.ImageField(blank=True, help_text='Примеры работ', upload_to='main/static/masters/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='masters',
            name='example4',
            field=models.ImageField(blank=True, help_text='Примеры работ', upload_to='main/static/masters/%Y/%m/%d'),
        ),
    ]
