# Generated by Django 3.1.2 on 2020-11-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201114_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='photo4',
        ),
    ]
