# Generated by Django 3.1.2 on 2020-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201114_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='photo1',
            field=models.ImageField(help_text='Добавить фото', upload_to='main/static/masters/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='master_1 или master_2'),
        ),
    ]
