# Generated by Django 3.1.2 on 2020-11-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Каталог услуг',
                'verbose_name_plural': 'Каталог услуг',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price_man', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Мужская стрижка, стоимость работы без материалов')),
                ('price_work', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Мужская стрижка, стоимость услуги')),
                ('price_man_material', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Мужская стрижка, расходные материалы')),
                ('price_man_all', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Мужская стрижка, стоимость работы')),
                ('price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены(от 25 до 40см)')),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены(от 25 до 40см)')),
                ('price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены(от 25 до 40см)')),
                ('price_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены(от 40 и выше)')),
                ('price_nm_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены без расходных материалов1')),
                ('price_nm_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены без расходных материалов2')),
                ('price_nm_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены без расходных материалов3')),
                ('price_nm_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цены без расходных материалов4')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.catalog')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
