# Generated by Django 3.1.2 on 2020-11-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201113_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_work',
        ),
    ]
