# Generated by Django 3.1.2 on 2020-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201113_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_man',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Мужская стрижка, стоимость работы без материалов'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_man_all',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Мужская стрижка, стоимость работы'),
        ),
    ]
