# Generated by Django 3.1.2 on 2020-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201113_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_man_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мужская стрижка, расходные материалы'),
        ),
    ]
