# Generated by Django 3.1.2 on 2020-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201113_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price_man_all',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мужская стрижка, стоимость работы'),
        ),
    ]
